version: "3.7"

services:
  breaking-news-api:
    build: . 
    image: breaking-news-api:local
    environment: 
      - HOST=0.0.0.0
      - VC_PORT=8000
      - API_PORT=8001
    ports:
      - 8000:8000
      - 8001:8001